version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - ".github/"
  - "config/"
  - "dist/"
  - "doc/"
  - "test/"
  - "types/"
  - "utl/"
  - "**/node_modules/"
  - "**/*.d.ts"
  - "src/parse/*parser.js"
  - "src/render/graphics/styling"
  - "src/render/graphics/csstemplates.ts"
  - "webpack.config.js"
