instrumentation:
    excludes: ['lib/**/*', 'indexAMD.js', 'doc/**/*', 'platoreports/**/*', 'coverage/**/*', 'render/graphics/styling/**', 'render/graphics/svgelementfactory/wobbly.js' ]
    include-all-sources: true
