#!/usr/bin/env node --disable-warning=DEP0040
/*
 * Reads an abstract syntax tree from stdin and writes the corresponding
 * scalable vector graphic to stdout
 * ### `ast2svg_nosource`
 * The only script remaining here. It takes an abstract syntax tree and renders
 * the SVG _without_ embedding the original source in it.
 *
 * ```sh
 *      ./tools/ast2svg_nosource < funkysyntaxtree.json > vectorgraphicswitoutsource.svg
 * ```
 *
 * or in combination with the command line interface:
 * ```sh
 *      node mscgen.js -p -i hello.mscin -o - | ./tools/ast2svg_nosource > hello_without_source.svg
 *  ```
 */

const JSDOM = require("jsdom").JSDOM;

const window = new JSDOM("<html><body></body></html>").window;
const renderast = require("../dist/cjs/render/graphics/renderast");

let gInput = "";

process.stdin.resume();
process.stdin.setEncoding("utf8");

process.stdin.on("data", function (pChunk) {
  gInput += pChunk;
});

process.stdin.on("end", function () {
  const lAST = JSON.parse(gInput);
  renderast.render(lAST, window, "__svg", {
    additionalTemplate: "inverted",
  });
  process.stdout.write(window.document.body.innerHTML);
  process.stdin.pause();
});
/*
 This file is part of mscgen_js.

 mscgen_js is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 mscgen_js is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with mscgen_js.  If not, see <http://www.gnu.org/licenses/>.
 */
